using Mockaroo.Model;
using Mockaroo.Model.DataTypes;
using Mockaroo.Services;
using MockarooLibrary.DataParsers;

//List<List<TableEntity>> entities = new();
//List<TableEntity> surnames = new();
//List<TableEntity> names = new();
//surnames.Add(new Surname("surname", "Klimenko"));
//surnames.Add(new Surname("surname", "Frolow"));
//surnames.Add(new Surname("surname", "Kisel"));
//surnames.Add(new Surname("surname", "Bogdanov"));
//names.Add(new Name("name", "Gleb"));
//names.Add(new Name("name", "Sergey"));
//names.Add(new Name("name", "Ivan"));
//names.Add(new Name("name", "andrey"));
//entities.Add(surnames);
//entities.Add(names);
//Table table = new Table("database", 4, entities);
//var service = new MockService(table);
//var query = await service.GenerateInsertStatement();
//query = null;
DataParser parser = new DataParser("Host=localhost;Port=5432;Database=Mockaroo;Username=postgres;Password=1312");
//parser.ParseAndInsertSurnamesFromTxt("C:\\Users\\gdklim10\\Downloads\\russian_surnames.txt");
//parser.ParseAndInsertNamesFromTxt("C:\\Users\\gdklim10\\Downloads\\russian_names.txt");
//parser.GenerateAndInsertRandomPhoneNumber(10000);
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address.txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (1).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (2).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (3).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (4).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (5).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (6).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (7).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (8).txt");
//parser.ParseAndInsertAddressFromTxt("C:\\Users\\gdklim10\\Downloads\\address (9).txt");